<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\Resources\Icon.ico</ApplicationIcon>
    <!-- Disable debug info to reduce size -->
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="..\Resources\Icon.ico" />
    <None Remove="..\Resources\Background.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\Resources\Background.png">
      <Link>Resources\Background.png</Link>
    </Resource>
    <Resource Include="..\Resources\Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
  </ItemGroup>

</Project>