<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWPF>false</UseWPF>
        <ApplicationIcon>..\Resources\Icon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <Resource Include="..\Resources\Icon.ico" />
        <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    </ItemGroup>

</Project>
